In [1]:
import pandas as pd 

o = pd.read_csv('./transformed/owners.csv')

In [3]:
len(o) - len(o.drop_duplicates('owner_id'))

8453

In [4]:
o.groupby(['owner_id']).size().sort_values()

owner_id
e39zc2v6fdfA     1
e3axF-XMmq44     1
e3aA5V4LFreS     1
e3_N5iV8T1Vb     1
e3ZTZ3VYYwVF     1
                ..
EoOk6YPMrU8H    10
jO2ZF-OwAjn8    11
6uW1sz1LLC0x    11
WdhX9J9FLdPP    11
xK_9YvWpybyo    15
Length: 104559, dtype: int64

In [5]:
o[o.owner_id == 'xK_9YvWpybyo']

,owner_id,activerentalregistrationflag,activecertificateapprovingrentaloccupancyflag,leadsafecertificateactiveflag,taxdelinquencyamount,transfers_in_5y,civil_tickets,complaints_health,code_violations,complaints_311,survey2022_grade_num,parcels_owned,std_deeded_owner
108290,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,"SUMMERHOUSE PROJECTS, LLC.,"
108291,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,SUMMERHOUSE PROJECTS LLC
108292,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,"SUMMERHOUSE PROJECTS, LLC"
108293,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,"SUMMERHOUSE PROJECTS, LLC"
108294,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,"SUMMERHOUSE PROJECTS, LLC"
108295,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,SUMMERHOUSE PROJECTS LLC
108296,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,SUMMERHOUSE PROJECTS LLC
108297,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,"SUMMERHOUSE PROJECTS , LLC"
108298,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,"SUMMERHOUSE PROJECTS, LLC"
108299,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,"SUMMERHOUSE PROJECTS LLC.,"
108300,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,"SUMMERHOUSE PROJECTS LLC.,"
108301,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,"SUMMERHOUSE PROJECTS, LLC.,"
108302,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,"SUMMERHOUSE PROJECTS LLC,"
108303,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,SUMMERHOUSE PROJECTS LLC
108304,xK_9YvWpybyo,47,5,12,146975.46,327,129.0,111.0,69.0,109.0,320.0,165,"SUMMERHOUSE PROJECTS, LLC"

In [4]:
for c in o.columns:
    print(c)

owner_id
activerentalregistrationflag
activecertificateapprovingrentaloccupancyflag
leadsafecertificateactiveflag
taxdelinquencyamount
transfers_in_5y
civil_tickets
complaints_health
code_violations
complaints_311
survey2022_grade_num
parcels_owned
std_deeded_owner

In [2]:
pd.set_option('display.max_columns', None)

In [24]:
par.sample()

,parcel,par_addr_all,parcel_predir,parcel_street,parcel_suffix,parcel_unit,neighborhood,parcel_owner,std_deeded_owner,grantor,grantee,last_transfer_date,tax_assessed_total,activerentalregistrationflag,activecertificateapprovingrentaloccupancyflag,leadsafecertificateactiveflag,transfers_in_5y,myplacelink,survey2022_grade,survey2022_photolink,taxdelinquencyamount,max_age,min_age,min_com_age,max_com_age,survey2022_grade_num,owner_id,parcel_addr_min,parcel_addr_max,civil_tickets,complaints_health,code_violations,complaints_311
63998,10609099,"1542 E 70 ST, CLEVELAND, OH, 44103",E,70,STREET,NaN,Hough,CLEVELAND LAND REUTILIZATION PROGRAM,CLEVELAND LAND BANK,"CLEMARK PROPERTY ASSOCIATES, LTD",CLEVELAND LAND REUTILIZATION PROGRAM,1.689789e+12,0.0,0,0,0,1,https://myplace.cuyahogacounty.gov/MTA2MDkwOTk...,NaN,https://wdwot.s3.amazonaws.com/blextoid/6384d8...,0.0,0.0,0.0,0.0,0.0,NaN,5-q9WC2Vw_VF,1542.0,1542.0,0.0,0.0,1.0,0.0

In [5]:
agg_cols = [ 
    'activerentalregistrationflag', 
    'activecertificateapprovingrentaloccupancyflag',
    'leadsafecertificateactiveflag',
    'taxdelinquencyamount',
    'transfers_in_5y',
    'civil_tickets',
    'complaints_health',
    'code_violations',
    'complaints_311',
    'survey2022_grade_num',
]

In [3]:
# agg_cols = [ 
#     'activerentalregistrationflag', 
#     'activecertificateapprovingrentaloccupancyflag',
#     'leadsafecertificateactiveflag',
#     'taxdelinquencyamount',
#     'transfers_in_5y',
#     'civil_tickets',
#     'complaints_health',
#     'code_violations',
#     'complaints_311',
#     'survey2022_grade_num',
# ]

# owners = par.groupby('owner_id')[agg_cols].sum().reset_index()
# par_count = (par
#     .groupby('owner_id')
#     .size()
#     .reset_index()
#     .rename(columns={0: 'parcels_owned'})
# )
# owners = owners.merge(par_count, on='owner_id')

In [21]:
par.sample()

,parcel,par_addr_all,parcel_predir,parcel_street,parcel_suffix,parcel_unit,neighborhood,parcel_owner,std_deeded_owner,grantor,grantee,last_transfer_date,tax_assessed_total,activerentalregistrationflag,activecertificateapprovingrentaloccupancyflag,leadsafecertificateactiveflag,transfers_in_5y,myplacelink,survey2022_grade,survey2022_photolink,taxdelinquencyamount,max_age,min_age,min_com_age,max_com_age,survey2022_grade_num,owner_id,parcel_addr_min,parcel_addr_max,civil_tickets,complaints_health,code_violations,complaints_311
26169,00701094,"4218 APPLE AVE, CLEVELAND, OH, 44113",NaN,APPLE,AVENUE,NaN,Ohio City,"DOSS, SHIRLEY A. & RAY, JOYCE M.","DOSS, SHIRLEY A. & RAY, JOYCE M.","Doss, Shirley A.","DOSS, SHIRLEY A. & RAY, JOYCE M.",7.873128e+11,59640.0,0,0,0,0,https://myplace.cuyahogacounty.gov/MDA3MDEwOTQ...,B,https://wdwot.s3.amazonaws.com/blextoid/63ea6a...,0.0,1900.0,1885.0,0.0,0.0,3.0,myvRVpYUhsNf,4218.0,4218.0,0.0,0.0,0.0,0.0

In [23]:
def summarize_with_count(df, keys, values, count_name=None):
    agg = df.groupby(keys)[values].sum().reset_index()
    if not count_name:
        return agg
    
    agg_count = (df
        .groupby(keys)
        .size()
        .reset_index()
        .rename(columns={0: count_name})
    )
    return agg.merge(agg_count, on=keys)

# agg_owners = summarize_with_count(par, ['owner_id'], agg_cols, 'parcels_owned')


# Owners by neighborhood.
owners_by_neighborhood = summarize_with_count(par, ['activerentalregistrationflag', 'neighborhood', 'owner_id'], agg_cols, 'parcels_owned')
owners_by_neighborhood_count = owners_by_neighborhood.groupby(['activerentalregistrationflag', 'neighborhood']).size().reset_index().rename(columns={0: 'owners'})

ValueError: cannot insert activerentalregistrationflag, already exists

In [20]:
a = owners_by_neighborhood.groupby('neighborhood')['taxdelinquencyamount'].quantile([x / 100 for x in range(5, 100, 5)]).reset_index()
a[a.neighborhood == a.sample().iloc[0]['neighborhood']]

               neighborhood  level_1  taxdelinquencyamount
19  Broadway-Slavic Village     0.05                 0.000
20  Broadway-Slavic Village     0.10                 0.000
21  Broadway-Slavic Village     0.15                 0.000
22  Broadway-Slavic Village     0.20                 0.000
23  Broadway-Slavic Village     0.25                 0.000
24  Broadway-Slavic Village     0.30                 0.000
25  Broadway-Slavic Village     0.35                 0.000
26  Broadway-Slavic Village     0.40                 0.000
27  Broadway-Slavic Village     0.45                 0.000
28  Broadway-Slavic Village     0.50                 0.000
29  Broadway-Slavic Village     0.55                 0.000
30  Broadway-Slavic Village     0.60                 0.000
31  Broadway-Slavic Village     0.65                 0.000
32  Broadway-Slavic Village     0.70                 0.000
33  Broadway-Slavic Village     0.75                 0.450
34  Broadway-Slavic Village     0.80               526.980
35  Broadway-Slavic Village     0.85              1532.798
36  Broadway-Slavic Village     0.90              3091.090
37  Broadway-Slavic Village     0.95              7693.678